# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
gems:
  - jemoji
gems:
  - jekyll-sitemap
  
# Setup
title:               Utkarsh Gupta
tagline:             'Self-Motivated. Balanced. Simple. Real'
description:         'Blog by Utkarsh Gupta <p>A curated list of ideas ,thoughts and random opinions on random topics</p>'
url:                 http://about.me/UtkarshGpta
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Utkarsh Gupta
  firstname:		 Utkarsh
  lastname:			 Gupta
  url:               https://twitter.com/UtkarshGpta
  email:             utkarshg1408@gmail.com

# Custom vars
version:             1.0.0
