# Site settings
title: "Utkarsh Gupta"
email: utkarshg1408@gmail.com
description: "Self learned developer and a student of Electrical Enginerring at IIT Roorkee."
keywords: "utkarshgpta, utkarsh gupta, developer, web, iit roorkee, jekyll, blog, personal, about me"
lang: "en"
author: "Utkarsh Gupta"
baseurl: ""
url: "http://utkarshgpta.com"
title_description: ""
title_image: "https://robohash.org/Utkarsh Gupta"
google_analytics: "UA-81663529-1"
disqus_account: UtkarshGpta
github_repository: https://github.com/utkarshgpta
addthis_id: ra-579c871df85f4998
post_limit: 3

# Social usernames/URLs
twitter_username: utkarshgpta
instagram_username: utkarsh.gpta
github_username:  utkarshgpta
linkedin_link: https://in.linkedin.com/in/utkarsh-gupta-33418b100
google_plus_link: https://plus.google.com/u/0/+UtkarshGupta404
stackoverflow_link: http://stackoverflow.com/users/5600195/utkarsh-gupta

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/UtkarshGpta\">Utkarsh Gupta</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/UtkarshGpta/UtkarshGpta.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
