# Site settings
title: "Utkarsh Gupta"
# title-description: " &#8226; "
email: utkarshg1408@gmail.com
description: "Senior Software Engineer - Innovation at Societe Generale Bengaluru. IIT Roorkee Alumni"
keywords: "utkarsh gupta, senior software engineer, full stack, blockchain, bangalore, iit roorkee, blog, personal, about me, societe generale"
lang: "en"
author:
  first_name: "Utkarsh"
  last_name: "Gupta"
baseurl: ""
url: "http://utkarshgpta.github.io/"

title_description: "I'm currently working as a Senior Software Engineer (Full-Stack) in Innovation Team at Societe Generale Bengaluru in the domain of Blockchain development, Full-Stack Web development, and Augmented Reality/Virtual Reality.
<br/><br/>
Before joining SocGen, I completed my undergraduate studies (B.Tech in Electrical Engineering) from the Indian Institute of Technology Roorkee.
I'm a self-learned developer who started off by googling - <i>\"how to make a website\"</i> and was awestruck as the color of the text on the screen changed as I did what was instructed.
<br/><br/>
I'm an open-source enthusiast who've tasted different waters of software engineering - Web development to Machine Learning to Blockchain, all in chronological order.
You can find me either binge-watching shows, listening to pop and progressive rock music, or surfing the tidal waves of the internet - primarily Reddit or HackerNews."

title_image: "//s.gravatar.com/avatar/78156753f9d8feaebe2418780bdc262b?s=250"
google_analytics: "UA-81663529-1"
disqus_account: utkarshgpta
github_repository: https://github.com/utkarshgpta
addthis_id: ra-579c871df85f4998
post_limit: 3

# Social usernames/URLs
twitter_username: utkarshgpta
instagram_username: utkarshgpta
facebook_username: UtkarshGpta
github_username:  utkarshgpta
linkedin_link: https://www.linkedin.com/in/utkarshgpta
google_plus_link: 

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/UtkarshGpta\">Utkarsh Gupta</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/UtkarshGpta/UtkarshGpta.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

gems:
  - jekyll-sitemap
  - jemoji
  
